export const causes = [
    "OnLevel",
    "OnPlayer",
    "OnActor",
    "OnDamage",
    "OnAlarm",
    "OnEventTrigger",
    "OnDialog",
    "OnReceiveNumber",
    "OnReceivePlayerHasItem",
    "OnEntity",
    "OnWaypoint",
];

export interface kcScriptFunction {
    name: string,
    script: boolean,
    sequence: boolean,
}

export const functions: kcScriptFunction[] = [
	{ name: "Entity.Activate", script: true, sequence: false },
	{ name: "Entity.Deactivate", script: true, sequence: false },
	{ name: "TerminateEntity", script: true, sequence: true },
	{ name: "SetFlags", script: true, sequence: true },
	{ name: "ClearFlags", script: true, sequence: true },
	{ name: "InitFlags", script: true, sequence: true },
	{ name: "SetTarget", script: true, sequence: false },
	{ name: "SetAnimationSpeed", script: true, sequence: true },
	{ name: "SetAxisPosition", script: true, sequence: false },
	{ name: "SetPosition", script: true, sequence: false },
	{ name: "AddToAxisPosition", script: true, sequence: false },
	{ name: "AddPosition", script: true, sequence: false },
	{ name: "SetAxisRotation", script: true, sequence: false },
	{ name: "SetRotation", script: true, sequence: false },
	{ name: "AddToAxisRotation", script: true, sequence: true },
	{ name: "AddRotation", script: true, sequence: true },
	{ name: "RotateRight", script: true, sequence: true },
	{ name: "RotateLeft", script: true, sequence: true },
	{ name: "LookAtTargetEntity", script: true, sequence: true },
	{ name: "SetAnimation", script: true, sequence: true },
	{ name: "SetSequence", script: true, sequence: false },
	{ name: "Wait", script: false, sequence: true },
	{ name: "WaitForAxisRotation", script: false, sequence: true },
	{ name: "WaitForFullRotation", script: false, sequence: true },
	{ name: "WaitForAnimation", script: false, sequence: true },
	{ name: "Loop", script: false, sequence: true },
	{ name: "Prompt", script: true, sequence: true },
	{ name: "ApplyImpulse", script: true, sequence: true },
	{ name: "ShowDialog", script: true, sequence: false },
	{ name: "SetAlarm", script: true, sequence: true },
	{ name: "TriggerEvent", script: true, sequence: true },
	{ name: "PlaySound", script: true, sequence: false },
	{ name: "SetVariable", script: true, sequence: false },
	{ name: "AddToVariable", script: true, sequence: false },
	{ name: "SendNumber", script: true, sequence: false },
	{ name: "SpawnParticleEffect", script: true, sequence: false },
	{ name: "KillParticleEffect", script: true, sequence: false },
	{ name: "SendPlayerHasItem", script: true, sequence: false },
	{ name: "SetPlayerHasItem", script: true, sequence: false },
	{ name: "TakeDamage", script: true, sequence: false },
	{ name: "SetSavePoint", script: true, sequence: false },
	{ name: "SetUpdatesEnabled", script: true, sequence: false },
	{ name: "Entity.EnableUpdates", script: true, sequence: false },
	{ name: "Entity.DisableUpdates", script: true, sequence: false },
	{ name: "SetAIGoal", script: true, sequence: false },
	{ name: "AttachSensor", script: true, sequence: false },
	{ name: "Attach", script: true, sequence: false },
	{ name: "Detach", script: true, sequence: false },
	{ name: "Entity.ActivateSpecial", script: true, sequence: false },
	{ name: "ActivateCamera", script: true, sequence: false },
	{ name: "DeactivateCamera", script: true, sequence: false },
	{ name: "SetCameraTarget", script: true, sequence: false },
	{ name: "SetCameraPivot", script: true, sequence: false },
	{ name: "SetCameraParam", script: true, sequence: false },
];

export const inSequenceFns: string[] = functions.filter((f) => f.sequence).map((f) => f.name);
export const outSequenceFns: string[] = functions.filter((f) => f.script).map((f) => f.name);